"""US trucking hub codes mapping — airports, Amazon facilities, informal terms.

resolve(code) returns (city, state) or None.
"""

from __future__ import annotations

from typing import Optional, Tuple

# Mapping of common trucking / logistics codes to (city, state).
# Includes: major airports (IATA), Amazon fulfilment-centre metro areas,
# informal trucker slang, and state abbreviations used as shorthand.
CITY_CODES: dict[str, Tuple[str, str]] = {
    # ── Major Airport / Metro Codes ──────────────────────────────────────
    "ATL": ("Atlanta", "GA"),
    "BNA": ("Nashville", "TN"),
    "BOS": ("Boston", "MA"),
    "BWI": ("Baltimore", "MD"),
    "CHS": ("Charleston", "SC"),
    "CLE": ("Cleveland", "OH"),
    "CLT": ("Charlotte", "NC"),
    "CMH": ("Columbus", "OH"),
    "CVG": ("Cincinnati", "OH"),
    "DAL": ("Dallas", "TX"),
    "DEN": ("Denver", "CO"),
    "DFW": ("Dallas-Fort Worth", "TX"),
    "DTW": ("Detroit", "MI"),
    "ELP": ("El Paso", "TX"),
    "EWR": ("Newark", "NJ"),
    "FLL": ("Fort Lauderdale", "FL"),
    "GSP": ("Greenville", "SC"),
    "HOU": ("Houston", "TX"),
    "IAD": ("Dulles", "VA"),
    "IAH": ("Houston", "TX"),
    "IND": ("Indianapolis", "IN"),
    "JAX": ("Jacksonville", "FL"),
    "JFK": ("New York", "NY"),
    "LAS": ("Las Vegas", "NV"),
    "LAX": ("Los Angeles", "CA"),
    "LGA": ("New York", "NY"),
    "MCI": ("Kansas City", "MO"),
    "MCO": ("Orlando", "FL"),
    "MDW": ("Chicago", "IL"),
    "MEM": ("Memphis", "TN"),
    "MIA": ("Miami", "FL"),
    "MKE": ("Milwaukee", "WI"),
    "MSP": ("Minneapolis", "MN"),
    "MSY": ("New Orleans", "LA"),
    "OAK": ("Oakland", "CA"),
    "OKC": ("Oklahoma City", "OK"),
    "OMA": ("Omaha", "NE"),
    "ONT": ("Ontario", "CA"),
    "ORD": ("Chicago", "IL"),
    "PBI": ("West Palm Beach", "FL"),
    "PDX": ("Portland", "OR"),
    "PHL": ("Philadelphia", "PA"),
    "PHX": ("Phoenix", "AZ"),
    "PIT": ("Pittsburgh", "PA"),
    "RDU": ("Raleigh", "NC"),
    "RIC": ("Richmond", "VA"),
    "RNO": ("Reno", "NV"),
    "RSW": ("Fort Myers", "FL"),
    "SAN": ("San Diego", "CA"),
    "SAT": ("San Antonio", "TX"),
    "SAV": ("Savannah", "GA"),
    "SDF": ("Louisville", "KY"),
    "SEA": ("Seattle", "WA"),
    "SFO": ("San Francisco", "CA"),
    "SJC": ("San Jose", "CA"),
    "SLC": ("Salt Lake City", "UT"),
    "SMF": ("Sacramento", "CA"),
    "STL": ("St. Louis", "MO"),
    "SYR": ("Syracuse", "NY"),
    "TPA": ("Tampa", "FL"),
    "TUL": ("Tulsa", "OK"),
    "TUS": ("Tucson", "AZ"),
    # ── Informal / Trucker Slang ─────────────────────────────────────────
    "SOCAL": ("Southern California", "CA"),
    "NOCAL": ("Northern California", "CA"),
    "NORCAL": ("Northern California", "CA"),
    "DMV": ("DC/Maryland/Virginia", "DC"),
    "TRISTATE": ("NY/NJ/CT Tri-State", "NY"),
    "TRI-STATE": ("NY/NJ/CT Tri-State", "NY"),
    "CHICAGOLAND": ("Chicago Metro", "IL"),
    "CHI": ("Chicago", "IL"),
    "CHITOWN": ("Chicago", "IL"),
    "NOLA": ("New Orleans", "LA"),
    "HOTLANTA": ("Atlanta", "GA"),
    "PHILLY": ("Philadelphia", "PA"),
    "JERSEY": ("New Jersey", "NJ"),
    "BMORE": ("Baltimore", "MD"),
    "INDY": ("Indianapolis", "IN"),
    "CINCI": ("Cincinnati", "OH"),
    "CINCY": ("Cincinnati", "OH"),
    "NASH": ("Nashville", "TN"),
    "JVILLE": ("Jacksonville", "FL"),
    "JAX": ("Jacksonville", "FL"),
    "SOFLO": ("South Florida", "FL"),
    "CENFLO": ("Central Florida", "FL"),
    "NOFLO": ("North Florida", "FL"),
    "DFLEX": ("Dallas-Fort Worth", "TX"),
    "HTOWNX": ("Houston", "TX"),
    "HTOWN": ("Houston", "TX"),
    "SA": ("San Antonio", "TX"),
    "RGV": ("Rio Grande Valley", "TX"),
    "IE": ("Inland Empire", "CA"),
    "INLAND EMPIRE": ("Inland Empire", "CA"),
    "BAY": ("Bay Area", "CA"),
    "BAY AREA": ("Bay Area", "CA"),
    "SEATAC": ("Seattle-Tacoma", "WA"),
    "PDX METRO": ("Portland Metro", "OR"),
    "TWIN CITIES": ("Minneapolis-St. Paul", "MN"),
    "KC": ("Kansas City", "MO"),
    "STL": ("St. Louis", "MO"),
    "COLA": ("Columbia", "SC"),
    "COLA SC": ("Columbia", "SC"),
    "COLA OH": ("Columbus", "OH"),
    "SAVANNAH": ("Savannah", "GA"),
    "LAREDO": ("Laredo", "TX"),
    "NOGALES": ("Nogales", "AZ"),
    "CALEXICO": ("Calexico", "CA"),
    # ── Amazon Fulfilment Centre Metro Areas ─────────────────────────────
    "BFI": ("Seattle", "WA"),        # Amazon HQ area
    "SBD": ("San Bernardino", "CA"),  # Inland Empire
    "ABE": ("Lehigh Valley", "PA"),
    "AVP": ("Wilkes-Barre", "PA"),
    "BDL": ("Hartford", "CT"),
    "BHM": ("Birmingham", "AL"),
    "BUF": ("Buffalo", "NY"),
    "CAE": ("Columbia", "SC"),
    "COS": ("Colorado Springs", "CO"),
    "DAY": ("Dayton", "OH"),
    "DSM": ("Des Moines", "IA"),
    "FAT": ("Fresno", "CA"),
    "FWA": ("Fort Wayne", "IN"),
    "GRR": ("Grand Rapids", "MI"),
    "GSO": ("Greensboro", "NC"),
    "HSV": ("Huntsville", "AL"),
    "ICT": ("Wichita", "KS"),
    "LEX": ("Lexington", "KY"),
    "LIT": ("Little Rock", "AR"),
    "LNK": ("Lincoln", "NE"),
    "MGM": ("Montgomery", "AL"),
    "MOB": ("Mobile", "AL"),
    "MSN": ("Madison", "WI"),
    "OKC": ("Oklahoma City", "OK"),
    "PNS": ("Pensacola", "FL"),
    "ROC": ("Rochester", "NY"),
    "SHV": ("Shreveport", "LA"),
    "TLH": ("Tallahassee", "FL"),
    "TYS": ("Knoxville", "TN"),
    "XNA": ("Fayetteville", "AR"),
    # ── State-abbreviation shorthand (used when context is state-wide) ───
    "AL": ("Alabama", "AL"),
    "AZ": ("Arizona", "AZ"),
    "AR": ("Arkansas", "AR"),
    "CA": ("California", "CA"),
    "CO": ("Colorado", "CO"),
    "CT": ("Connecticut", "CT"),
    "DE": ("Delaware", "DE"),
    "FL": ("Florida", "FL"),
    "GA": ("Georgia", "GA"),
    "ID": ("Idaho", "ID"),
    "IL": ("Illinois", "IL"),
    "IN": ("Indiana", "IN"),
    "IA": ("Iowa", "IA"),
    "KS": ("Kansas", "KS"),
    "KY": ("Kentucky", "KY"),
    "LA": ("Louisiana", "LA"),
    "ME": ("Maine", "ME"),
    "MD": ("Maryland", "MD"),
    "MA": ("Massachusetts", "MA"),
    "MI": ("Michigan", "MI"),
    "MN": ("Minnesota", "MN"),
    "MS": ("Mississippi", "MS"),
    "MO": ("Missouri", "MO"),
    "MT": ("Montana", "MT"),
    "NE": ("Nebraska", "NE"),
    "NV": ("Nevada", "NV"),
    "NH": ("New Hampshire", "NH"),
    "NJ": ("New Jersey", "NJ"),
    "NM": ("New Mexico", "NM"),
    "NY": ("New York", "NY"),
    "NC": ("North Carolina", "NC"),
    "ND": ("North Dakota", "ND"),
    "OH": ("Ohio", "OH"),
    "OK": ("Oklahoma", "OK"),
    "OR": ("Oregon", "OR"),
    "PA": ("Pennsylvania", "PA"),
    "RI": ("Rhode Island", "RI"),
    "SC": ("South Carolina", "SC"),
    "SD": ("South Dakota", "SD"),
    "TN": ("Tennessee", "TN"),
    "TX": ("Texas", "TX"),
    "UT": ("Utah", "UT"),
    "VT": ("Vermont", "VT"),
    "VA": ("Virginia", "VA"),
    "WA": ("Washington", "WA"),
    "WV": ("West Virginia", "WV"),
    "WI": ("Wisconsin", "WI"),
    "WY": ("Wyoming", "WY"),
    "DC": ("Washington DC", "DC"),
}


def resolve(code: str) -> Optional[Tuple[str, str]]:
    """Resolve a trucking hub code to (city, state) or return None.

    Lookup is case-insensitive and strips whitespace.
    """
    normalised = code.strip().upper()
    return CITY_CODES.get(normalised)
